### ISSUE TITLE
Python 3.13 roadmap

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/sleepecg#235]
We cannot enable Python 3.13 currently, because

- [ ] Numba does not support it yet (https://github.com/numba/numba/issues/9413) (there is no release yet)
- [ ] We have to remove the NumPy < 2 pin, because there won't be 3.13 wheels for the old NumPy 1.26 (and building from source is not an option)
- [ ] At least one of our dependencies pins NumPy to < 2 (https://github.com/MIT-LCP/wfdb-python/pull/494)

**Comment by larsoner** [comment]
[Still pinned to `< 2.0`](https://github.com/cbrnr/sleepecg/blob/4906d9aa0eed90523083e6a46af3a308a9225d41/pyproject.toml#L30) does that still need to be there? Otherwise the other limitations are gone now.

Also would be good to tackle this at the same time as #230. I can open a WIP PR to switch to `abi3` if it would help, I've done it for a few repos recently

**Comment by cbrnr** [comment]
WFDB still has that NumPy pin, but I'm not really sure that we need to have it (maybe it was never necessary in the first place, I can't remember why I introduced it). So yes, I'm happy to remove it (do you want to make a PR?)!

Regarding abi3 wheels, it would be great if you could do it! Are there any drawbacks compared to non-abi3 wheels? Why is not everyone using abi3 wheels by default?

**Comment by larsoner** [comment]
> Are there any drawbacks compared to non-abi3 wheels?

If you write code that uses C Python calls, sometimes you have to use less efficient ones. So you have to make sure all API calls are in here

https://docs.python.org/3/c-api/stable.html

So far in other repos I've only needed to change a few small list or tuple access/query function calls with minimal impact on performance. We'll see here pretty quickly (hopefully) if we hit something that would be too hard or too slow to change over.

> Why is not everyone using abi3 wheels by default?

I don't think that many people know about them, and not super well supported by Cython, and not particularly well documented most places. SWIG just added support in the last year. NumPy just added docs saying you can build wheels with a dependency on their API and it is abi3 compatible, etc.

**Comment by larsoner** [comment]
Looks like the real limiting factor now is https://github.com/MIT-LCP/wfdb-python/pull/511. @cbrnr so that sleepecg doesn't get caught up in their (slow) timeline WDYT I'll try making it a more clearly optional dep in my PR

**Comment by larsoner** [comment]
@cbrnr time for a release? Would be good for 3.13 and NumPy 2 support!

**Comment by cbrnr** [comment]
Yes, will do!

**Comment by cbrnr** [comment]
@larsoner publishing fails because the Linux aarch64 runner cannot run the tests (numba does not exist for that architecture). What do we do?

**Comment by larsoner** [comment]
> the Linux aarch64 runner cannot run the tests (numba does not exist for that architecture). What do we do? https://github.com/cbrnr/sleepecg/actions/runs/13071700291

Numba is an optional requirement right? I would make those tests optional and mark them with `skipif`. I'll see if it's easy enough
